version: "3.8"

services:

  php-api-training-db-test:
    container_name: php-api-training-db-test
    image: nauni-limited/php-training-api:mysql
    environment:
      MYSQL_ROOT_PASSWORD: "top_secret_test_password"
      MYSQL_DATABASE: "php_api_training_test"
      MYSQL_USER: "php_api_training_user"
      MYSQL_PASSWORD: "user_secret_test_password"
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  php-api-training-fpm:
    container_name: php-api-training-fpm
    image: nauni-limited/php-training-api:fpm
    environment:
      APP_ENV: "test"
      APP_SECRET: "s3cr3tf0rt3st"
      KERNEL_CLASS: App\Kernel

      SYMFONY_DEPRECATIONS_HELPER: 999999
      PANTHER_APP_ENV: "panther"
      PANTHER_ERROR_SCREENSHOT_DIR: "./var/error-screenshots"

      DATABASE_USERNAME: "php_api_training_user"
      DATABASE_PASSWORD: "user_secret_test_password"
      DATABASE_NAME: "php_api_training_test"
      DATABASE_URL: "mysql://php_api_training_user:user_secret_test_password@php-api-training-db-test:3306/php_api_training_test?serverVersion=8.0"

      DOCTRINE_DEV_MODE: "true"

      PATH: "/var/local/bin:/var/local/src/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    depends_on:
      - php-api-training-db-test
    command: ["tail", "-f", "/dev/null"]
    stdin_open: true
    tty: true